language: node_js
node_js:
- 6
os: linux
dist: trusty
sudo: required
cache:
  yarn: true
branches:
  only:
  - master
install:
- |
    yarn install
    yarn run bootstrap
script:
- |
    yarn lint
    yarn test
