version: 2
jobs:
  build:
    docker:
      - image: node:6.10.0
    working_directory: ~/youzan/zent
    steps:
      - checkout
      - run:
          name: Pre-Dependencies
          command: |
            curl -o- -L https://yarnpkg.com/install.sh | bash
      - run:
          name: Install Dependencies
          command: |
            yarn install
      - run:
          name: NPM Test
          command: |
            yarn bootstrap
            yarn lint
            yarn test
